sudo: false
language: python
dist: focal
cache: pip
python:
- '3.8'
- '3.9'
- '3.10'
- '3.11'
- '3.12'
install:
- sudo apt update
- sudo apt upgrade
- sudo apt install rustc cargo
- pip install tox-travis
script: tox

