---
# https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration
extends: default

ignore: |
  ^deployment/charts

rules:
  document-start:
    level: error
  document-end:
    level: error
...
