apiVersion: v2
name: tesk
description: A TESK-EXILIR Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: dev
dependencies:
  - name: nginx-ingress
    condition: ingress.nginx
    repository: oci://registry-1.docker.io/nginxcharts
    version: 1.1.2