{{ if .Values.ftp.classic_ftp_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ftp.classic_ftp_secret }}
type: Opaque
stringData:
  username: {{ .Values.ftp.username }}
  password: {{ .Values.ftp.password }}
{{ end }}
