{{ if .Values.ftp.hostip }}
kind: Endpoints
apiVersion: v1
metadata:
    name: ftp
subsets:
    - addresses:
        - ip: {{ .Values.ftp.hostip }}  # ipv4 address from vboxnet0
      ports:
        - port: 21
{{ end }}
