{{ if .Values.ftp.netrc_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ftp.netrc_secret }}
type: Opaque
stringData:
  .netrc: |-
{{ .Files.Get "ftp/.netrc" | indent 4 }}
{{ end }}
