{{ if eq .Values.auth.mode "auth" }}
apiVersion: v1
stringData:
  id: {{ .Values.auth.client_id }}
  secret: {{ .Values.auth.client_secret }}
kind: Secret
metadata:
  name: oauth-client-secret
type: Opaque
{{ end }}
