#!/bin/bash
#
# Usage:
#
#     buildDockerImage filer          or
#     buildDockerImage taskmaster
#

IMAGE=$1

if [ -z "$IMAGE" ];
then
  echo "Use: $0 <filer/taskmaster> [tag]"
  exit 12
fi

TAG=$2

if [ -z "$TAG" ];
then
  TAG=testing
fi

if command -V buildah;
then
  buildah bud -t "docker.io/elixircloud/tesk-core-$IMAGE:$TAG" \
    --format=docker --no-cache \
    -f "containers/$IMAGE.Dockerfile"
else
  docker build -t "docker.io/elixircloud/tesk-core-$1:$TAG" -f "containers/$1.Dockerfile" .
fi
