---
name: Code Test Unit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        id: ct
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install test dependencies
        run: poetry install --only=test --no-interaction

      - name: Run tests and generate coverage as test_unit.xml
        run: |
          poetry run pytest \
            --cov-report term \
            --cov-report xml:test_unit.xml \
            --cov=tests/test_unit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: test_unit
          files: ./test_unit.xml
          fail_ci_if_error: true
          verbose: true
