name: Code Test Unit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install poetry
        run: pipx install poetry

      - name: Generate hash of tesk with test dependencies only
        run: |
          poetry export --with=lint --format=requirements.txt --output=requirements.txt
          echo "hash=$(sha256sum requirements.txt | cut -d ' ' -f 1)" >> $GITHUB_ENV

      - name: Cache dependencies
        id: ctuut
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
          key: ${{ runner.os }}-test-${{ env.hash }}
          restore-keys: |
            ${{ runner.os }}-test-

      - name: Check cache hit
        run: |
          echo "Cache hit status: ${{ steps.ctuut.outputs.cache-hit }}"

      - name: Install test dependencies
        if: steps.ctuut.outputs.cache-hit != 'true'
        run: poetry install --only=test --no-interaction

      - name: Run tests and generate coverage as test_unit.xml
        run: poetry run pytest --cov-report term --cov-report xml:test_unit.xml --cov=tests/test_unit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: test_unit
          files: ./test_unit.xml
          fail_ci_if_error: true
          verbose: true
