---
name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  general-checks:
    name: General checks
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: 'actions/setup-python@v5'
        id: setup-python
        with:
          python-version: '3.11'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit checks
        run: pre-commit run --all-files

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup/poetry
        with:
          os: ${{ job.os }}
          python-version: '3.11'
          poetry-install-options: "--only=lint --no-root"
          poetry-export-options: "--only=lint"

      - name: Check code quality
        run: poetry run ruff check .

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup/poetry
        with:
          os: ${{ job.os }}
          python-version: '3.11'
          poetry-install-options: "--only=lint --no-root"
          poetry-export-options: "--only=lint"

      - name: Check code style
        run: poetry run ruff format --check

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup/poetry
        with:
          os: ${{ job.os }}
          python-version: '3.11'
          poetry-install-options: "--only=types --no-root"
          poetry-export-options: "--only=types"

      - name: Check types
        run: poetry run mypy tesk/

  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup/poetry
        with:
          os: ${{ job.os }}
          python-version: '3.11'
          poetry-install-options: "--only=lint --no-root"
          poetry-export-options: "--only=lint"

      - name: Check spellings
        run: poetry run typos .
...
