name: Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry

    # Set up python versions with matrix to test on multiple versions
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # Install dependencies if cache does not exist
    - name: Install dependencies
      run: poetry install

    # Run tests
    - name: Run tests
      run: poetry run pytest tests/

    # # Upload coverage reports to Codecov once the tests start running 😭
    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v3
    #   env:
    #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}