name: Vulnerability Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up python
        id: vt
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'

      # Install only type check dependency
      - name: Install dependencies
        if: steps.vt.outputs.cache-hit != 'true'
        run: poetry install --only=security --no-root

      - name: Check types
        run: poetry run bandit -c pyproject.toml -r tesk/

  dependency-vulnerabilities:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up python
        id: vt
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'

      # Install only type check dependency
      - name: Install dependencies
        if: steps.vt.outputs.cache-hit != 'true'
        run: poetry install --only=security --no-root

      - name: Check types
        run: poetry run safety check --full-report
